---
id: tokyodebian-porterbox-20160305
base_name: tokyodebian-porterbox
tags:
- debian
presentation_date: 
version: 1.0.0
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: HAYASHI Kentaro
  email: kenhys@gmail.com
  rubygems_user: kenhys
  slideshare_user: 
  speaker_deck_user: 
